### ISSUE TITLE
Simultaneous modification of CalioDynamicRegistryManager.registries during packet processing

### ISSUE THREAD

**Issue by jlortiz0** [EdwinMindcraft/calio#3]
### Version
Confirmed on 1.19.x/forge aece46ed, buildscript 1.19.x/forge [e4f58032](https://github.com/EdwinMindcraft/origins-forge/tree/e4f5803205834f608b162709c024e4b9c02ede01)
Although the structure of the code in `HolderCodec` is different, this bug also seems to apply to 1.20.x/forge.

### Problem
When the client receives multiple `S2CDynamicRegistryPacket`s for the same registry, it will decode and handle them concurrently. However, the call(s) to `access.get` in `HolderCodec.decode` may happen concurrently with the call to `CalioDynamicRegistryManager.reset` in `S2CDynamicRegistryPacket.handle`. If this occurs, the call to `access.get` may fail with IllegalArgumentException.

### Potential Solutions
I was able to fix the problem on a local copy by placing locks around accesses to `CalioDynamicRegistryManager.registries`. However, this came with a performance penalty. A better solution may be to remove the call to `registries.remove` in `CalioDynamicRegistryManager.reset`, but I am unsure of the potential regressions of that change.

### Other Mods
In order to force the packets to be split, I used [Origins++](https://www.curseforge.com/minecraft/mc-mods/origins-plus-plus/files/4763246). However, this could occur with any sufficiently large datapack.

### Related Bugs
I suspect this to be the cause of EdwinMindcraft/origins-architectury#405 and its duplicates.

**Comment by jlortiz0** [comment]
Adding on to this, multiple instances of `S2CDynamicRegistryPacket.handle` can execute concurrently, which can cause a CME that passes silently and is thus difficult to detect.

**Comment by ChrysanthCow** [comment]
Thanks for looking into it, while I didn't read this at first, removing the call to `registries.remove` was the fix I went with.

**Comment by ChrysanthCow** [comment]
I'm going to leave this open while the CME issue can happen.

I don't think anything bad would happen without the call to `registries#remove`, mainly because we add stuff back under the same key, the main issue I could see is new content being added to the old registry, and the registry then being reset.

**Comment by ChrysanthCow** [comment]
Edwin and I went with the lock solution, despite the potential performance impact, it's more important that Origins actually get loaded, rather than having a data race for an unnoticeable performance gain.
