### ISSUE TITLE
ClientHelper.isServerContext returns false in singleplayer worlds

### ISSUE THREAD

**Issue by jlortiz0** [EdwinMindcraft/calio#4]
### Version
Confirmed on 1.19.x/forge aece46ed, buildscript 1.19.x/forge [e4f58032](https://github.com/EdwinMindcraft/origins-forge/tree/e4f5803205834f608b162709c024e4b9c02ede01)
~~Not yet confirmed~~ Does not occur on 1.20.x/forge.

### Problem
When in singleplayer, the `RegistryAccess` used by the internal server appears to be obtained from `RegistryAccess.BUILTIN`. The code in `ClientHelper.isServerContext` assumes that this is not the case, and thus always returns false. This can cause datapack reloads in singleplayer to unexpectedly fail as the server will attempt to send the client's registries to the client.

### Potential Solutions
Aside from one instance in [origins-architectury:PartialOrigin.Builder.powers](https://github.com/EdwinMindcraft/origins-architectury/blob/afdfc32c49efece28b3ca0d3d99839ab669faf6f/src/main/java/io/github/edwinmindcraft/origins/api/data/PartialOrigin.java#L131), the `access` argument is always null. As such, it may be possible to remove the comparison to `RegistryAccess.BUILTIN` and just use the null check. This may have some regressions, and I suspect that a better solution exists.

**Comment by jlortiz0** [comment]
Confirmed that this does **not** occur on 1.20.1. Seems this is limited to 1.19 (or even that specific version of Forge). Leaving this open for now in case you want to take another look at it anyway.

**Comment by ChrysanthCow** [comment]
The commits above aren't the true fix I feel, I'm going to keep the original logic, but also include a check for `!ServerLifecycleHooks.getCurrentServer().isDedicatedServer()`
